drop table if exists library CASCADE;
drop table if exists user CASCADE;

create table library (
id bigint generated by default as identity, 
isbn10 bigint, 
isbn13 varchar(255), 
author varchar(255), 
book_title varchar(255) not null, 
pages integer not null, 
qty integer not null,
availability boolean not null,
primary key (id)
); 

create table user (
id bigint generated by default as identity, 
age integer not null, 
first_name varchar(255) not null, 
last_name varchar(255), 
password varchar(255), 
user_name varchar(255), 
library_id bigint, 
primary key (id)
);

alter table user add constraint FKbfbrr0di61ixdf940wfbd9v6r foreign key (library_id) references library on delete cascade;