drop table if exists library CASCADE; 
drop table if exists user CASCADE;

create table library (
id bigint generated by default as identity, 
isbn10 integer not null, 
isbn13 varchar(255), 
author varchar(255), 
availability boolean not null, 
book_title varchar(255) not null, 
pages integer not null, 
qty integer not null, 
users_id bigint, 
primary key (id)
);

create table user (
id bigint generated by default as identity, 
age integer not null, 
first_name varchar(255) not null, 
last_name varchar(255), 
password varchar(255), 
user_name varchar(255), 
primary key (id)
);

alter table library add constraint FK4lmqtyr42vg4u429iwtckxy0n foreign key (users_id) references user on delete cascade;