drop table if exists library CASCADE;
drop table if exists users CASCADE;

create table library (
id bigint generated by default as identity, 
author varchar(255),  
book_title varchar(255) not null, 
genre varchar(255), 
pages integer not null, 
qty integer not null, 
users_id bigint, 
primary key (id)
);

create table users (
id bigint generated by default as identity, 
email_address varchar(255), 
first_name varchar(255) not null, 
last_name varchar(255), 
password varchar(255), 
user_name varchar(255), 
primary key (id)
);

alter table library add constraint FK1t3ygn1w067n6kw75d7wks586 foreign key (users_id) references users on delete cascade;
